<a href="https://colab.research.google.com/github/gkondayya/testGit/blob/master/Tec_w_Tim_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
# First note book based on 7 hour tutorial on TF by Tech with Tim
%tensorflow_version 2.x # no longer rquired !!
import tensorflow as tf
print(tf.version)

`%tensorflow_version` only switches the major version: 1.x or 2.x.
You set: `2.x # no longer rquired !!`. This will be interpreted as: `2.x`.


TensorFlow is already loaded. Please restart the runtime to change versions.
<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow/_api/v2/version/__init__.py'>


# Rank and shape of Tensors

In [43]:
# Scalars
string  = tf.Variable("this is string",tf.string)
floatnumber = tf.Variable(3.0,tf.float32) 
integer = tf.Variable(3,tf.int16)
# Scalars are tensors of rank 0
print(tf.rank(integer))


# Tensor of rank 1 (1D arrays or vectors) [ 1,2,3 ]
tensor_of_rank_1 = tf.Variable([3,4,5],tf.int16)
print(tf.rank(tensor_of_rank_2))
print(tensor_of_rank_2.shape)

# Tensor of rank 2 (2D Matrices) [ [1,2,3], [3,4,5] ]

tensor_of_rank_2 = tf.Variable([[3,5]],tf.int16)
print(tf.rank(tensor_of_rank_2))
print(tensor_of_rank_2.shape)

# Layers of 2D matrices
# Tensors of rank 3 (3D Matrices) [  [[1,2,3], [4,5,6]], [[7,8,9], [1,4,5]]   ]
                                    # matrix in layer1    # matrix in layer 2             

threeD111 = tf.Variable([  [[1]]  ],tf.int16)
print(threeD111.shape)
print(tf.rank(threeD111))

threeD112 = tf.Variable([  [[1,2]]  ],tf.int16)
print(threeD112.shape)

threeD113 = tf.Variable([  [[1,2,3]]  ],tf.int16)
print(threeD113.shape)

threeD123 = tf.Variable([  [[1,2,3],[4,5,6]]  ],tf.int16)
print(threeD123.shape)

threeD133 = tf.Variable([  [ [1,2,3],[4,5,6],[7,8,9] ]  ],tf.int16)
print(threeD133.shape)


threeD233 = tf.Variable([  [ [1,2,3],[4,5,6],[7,8,9] ],  [ [1,2,3],[4,5,6],[7,8,9] ]  ],tf.int16)
print(threeD233.shape)

threeD333 = tf.Variable([   [[1,2,3],[4,5,6],[7,8,9]],  [[1,2,3],[4,5,6],[7,8,9]], [[1,2,3],[4,5,6],[7,8,9]]  ],tf.int16)
print(threeD333.shape)



tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
(1, 2)
tf.Tensor(2, shape=(), dtype=int32)
(1, 2)
(1, 1, 1)
tf.Tensor(3, shape=(), dtype=int32)
(1, 1, 2)
(1, 1, 3)
(1, 2, 3)
(1, 3, 3)
(2, 3, 3)
(3, 3, 3)


# Reshape function

In [44]:
threeD321 = tf.reshape(threeD123, [3,2,1])
print(threeD321)

tf.Tensor(
[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]], shape=(3, 2, 1), dtype=int32)


In [45]:
# Effect of the Above operation is same as following declaration  
threeD321 = tf.Variable([  [[1],[2]], [[3],[4]], [[5],[6]]  ],tf.int16)
print(threeD321)

<tf.Variable 'Variable:0' shape=(3, 2, 1) dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]], dtype=int32)>


In [46]:
# Reshape with -1 to reduce dimension

threeD321_to_32 = tf.reshape(threeD123, [3,-1])
print(threeD321_to_32)

# Another example
threeD333_to_2Dmatrix = tf.reshape(threeD333, [3,-1])
print(threeD333_to_2Dmatrix)


tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]], shape=(3, 9), dtype=int32)


# Evaluating Tensors

In [47]:
with tf.Session() as sess:
  threeD321.eval()

AttributeError: ignored